DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
    'Main', 'Snack', 'Lunch', 'Breakfast'
);

CREATE TABLE IF NOT EXISTS shopping_list (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    item_name TEXT NOT NULL, 
    price decimal(12,2) NOT NULL,
    checked BOOLEAN DEFAULT false,
    date_added TIMESTAMPTZ DEFAULT now(),
    category grocery NOT NULL
);