INSERT INTO blogful (title, content, date_published)
VALUES 
('Robin Hood', 'Steal from the rich to give to the needy', now()),
('Queen', 'Is this the real life?', now()),
('Bon Jovi', 'Shot through the heart and you''re to blame', now()),
('Elton John', 'Don''t go breaking my heart', now()),
('Dire Straits', 'Money for nothing', now()),
('The Rembrandts', 'I''ll be there for you', now()),
('Blue October', 'Into the Ocean', now()),
('Oasis', 'Wonderwall', now()),
('Good Charlotte', 'The Anthem', now()),
('Blink-182', 'What''s my age again?', now()),
('Aerosmith', 'Back in the saddle again', now()),
('The Police', 'Every step you take', now()),
('Judas Priest', 'Breaking the law', now()),
('AC/DC', 'For those about to rock', now()),
('Alice Cooper', 'School''s out for summer', now()),
('Led Zepplin', 'Over the hills and far away', now()),
('Star Wars', 'Vader''s march', now()),
('Blink-182', 'Steal from the rich to give to the needy', now()),
('Robin Hood', 'Steal from the rich to give to the needy', now()),
('Robin Hood', 'Steal from the rich to give to the needy', now()),
